CXXFLAGS=-Wall -Wextra -O2 -std=c++17

1:
	g++ ./main.cpp -std=gnu++17 -I ~/contests/ac-library
	date; ./a.out < ../../problems.kyopro/1.kyopro > ../../solutions/1-johniel2.json

2:
	g++ ./main.cpp -std=gnu++17 -I ~/contests/ac-library
	date; ./a.out < ../../problems.kyopro/2.kyopro > ../../solutions/2-johniel2.json

3:
	g++ ./main.cpp -std=gnu++17 -I ~/contests/ac-library
	date; ./a.out < ../../problems.kyopro/3.kyopro > ../../solutions/3-johniel2.json


11:
	g++ ./main.cpp -std=gnu++17 -I ~/contests/ac-library
	date; ./a.out < ../../problems.kyopro/11.kyopro > ../../solutions/11-johniel2.json

12:
	g++ ./main.cpp -std=gnu++17 -I ~/contests/ac-library
	date; ./a.out < ../../problems.kyopro/12.kyopro > ../../solutions/12-johniel2.json


17:
	g++ ./main.cpp -std=gnu++17 -I ~/contests/ac-library
	date; ./a.out < ../../problems.kyopro/17.kyopro > ../../solutions/17-johniel2.json

19:
	g++ ./main.cpp -std=gnu++17 -I ~/contests/ac-library
	date; ./a.out < ../../problems.kyopro/19.kyopro > ../../solutions/19-johniel2.json


all:
	g++ ./main.cpp -std=gnu++17 -I ~/contests/ac-library
	date; ./a.out < ../../problems.kyopro/1.kyopro > ../../solutions/1-johniel2.json
	date; ./a.out < ../../problems.kyopro/2.kyopro > ../../solutions/2-johniel2.json
	date; ./a.out < ../../problems.kyopro/3.kyopro > ../../solutions/3-johniel2.json
	date; ./a.out < ../../problems.kyopro/4.kyopro > ../../solutions/4-johniel2.json
	date; ./a.out < ../../problems.kyopro/5.kyopro > ../../solutions/5-johniel2.json
	date; ./a.out < ../../problems.kyopro/6.kyopro > ../../solutions/6-johniel2.json
	date; ./a.out < ../../problems.kyopro/7.kyopro > ../../solutions/7-johniel2.json
	date; ./a.out < ../../problems.kyopro/8.kyopro > ../../solutions/8-johniel2.json
	date; ./a.out < ../../problems.kyopro/9.kyopro > ../../solutions/9-johniel2.json
	date; ./a.out < ../../problems.kyopro/10.kyopro > ../../solutions/10-johniel2.json
	date; ./a.out < ../../problems.kyopro/11.kyopro > ../../solutions/11-johniel2.json
	date; ./a.out < ../../problems.kyopro/12.kyopro > ../../solutions/12-johniel2.json
	date; ./a.out < ../../problems.kyopro/13.kyopro > ../../solutions/13-johniel2.json
	date; ./a.out < ../../problems.kyopro/14.kyopro > ../../solutions/14-johniel2.json
	date; ./a.out < ../../problems.kyopro/15.kyopro > ../../solutions/15-johniel2.json
	date; ./a.out < ../../problems.kyopro/16.kyopro > ../../solutions/16-johniel2.json
	date; ./a.out < ../../problems.kyopro/17.kyopro > ../../solutions/17-johniel2.json
	date; ./a.out < ../../problems.kyopro/18.kyopro > ../../solutions/18-johniel2.json
	date; ./a.out < ../../problems.kyopro/19.kyopro > ../../solutions/19-johniel2.json
	date; ./a.out < ../../problems.kyopro/20.kyopro > ../../solutions/20-johniel2.json
	date; ./a.out < ../../problems.kyopro/21.kyopro > ../../solutions/21-johniel2.json
	date; ./a.out < ../../problems.kyopro/22.kyopro > ../../solutions/22-johniel2.json
	date; ./a.out < ../../problems.kyopro/23.kyopro > ../../solutions/23-johniel2.json
	date; ./a.out < ../../problems.kyopro/24.kyopro > ../../solutions/24-johniel2.json
	date; ./a.out < ../../problems.kyopro/25.kyopro > ../../solutions/25-johniel2.json
	date; ./a.out < ../../problems.kyopro/26.kyopro > ../../solutions/26-johniel2.json
	date; ./a.out < ../../problems.kyopro/27.kyopro > ../../solutions/27-johniel2.json
	date; ./a.out < ../../problems.kyopro/28.kyopro > ../../solutions/28-johniel2.json
	date; ./a.out < ../../problems.kyopro/29.kyopro > ../../solutions/29-johniel2.json
	date; ./a.out < ../../problems.kyopro/30.kyopro > ../../solutions/30-johniel2.json
	date; ./a.out < ../../problems.kyopro/31.kyopro > ../../solutions/31-johniel2.json
	date; ./a.out < ../../problems.kyopro/32.kyopro > ../../solutions/32-johniel2.json
	date; ./a.out < ../../problems.kyopro/33.kyopro > ../../solutions/33-johniel2.json
	date; ./a.out < ../../problems.kyopro/34.kyopro > ../../solutions/34-johniel2.json
	date; ./a.out < ../../problems.kyopro/35.kyopro > ../../solutions/35-johniel2.json
	date; ./a.out < ../../problems.kyopro/36.kyopro > ../../solutions/36-johniel2.json
	date; ./a.out < ../../problems.kyopro/37.kyopro > ../../solutions/37-johniel2.json
	date; ./a.out < ../../problems.kyopro/38.kyopro > ../../solutions/38-johniel2.json
	date; ./a.out < ../../problems.kyopro/39.kyopro > ../../solutions/39-johniel2.json
	date; ./a.out < ../../problems.kyopro/40.kyopro > ../../solutions/40-johniel2.json
	date; ./a.out < ../../problems.kyopro/41.kyopro > ../../solutions/41-johniel2.json
	date; ./a.out < ../../problems.kyopro/42.kyopro > ../../solutions/42-johniel2.json
	date; ./a.out < ../../problems.kyopro/43.kyopro > ../../solutions/43-johniel2.json
	date; ./a.out < ../../problems.kyopro/44.kyopro > ../../solutions/44-johniel2.json
	date; ./a.out < ../../problems.kyopro/45.kyopro > ../../solutions/45-johniel2.json
