name: PullRepo

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Pull /home/ubuntu/repo
        run: cd /home/ubuntu/repo && git pull
      - name: Pull /home/ubuntu/dashboard
        run: cd /home/ubuntu/dashboard && git pull
