name: PullRepo

on:
  schedule:
    - cron:  '0 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Pull /home/ubuntu/repo
        run: cd /home/ubuntu/repo && git pull
