name: Submit

on:
  push:
    branches: [ "main" ]
    paths: ["solutions/*.json"]
  workflow_dispatch:

jobs:
  build:
    runs-on: [runner1]
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: ci_submit
        run: ICFPC_TOKEN=$(cat /home/ubuntu/ICFPC_TOKEN) python3 ci_submit.py
      - name: commit
        run: git add solutions/*.submission; git commit -m "ci_submit"; git pull; git push
