name: Submit

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [runner1]

    steps:
      - uses: actions/checkout@v2
      - name: ci_submit
        run: python3 ci_submit.py
